### PR TITLE
http links to https in nuspec

### PR DESCRIPTION
**Pull request by 304NotModified**
followup of [nunit/nunit#3160](https://github.com/nunit/nunit/pull/3160) ;)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Polite bump

**Comment by 304NotModified** [comment]
bump @ChrisMaddock

**Comment by CharliePoole** [comment]
@304NotModified Not sure why you're picking on Chris. :smiley:

Each of these  repositories has somebody person in charge. This one in particular belongs to @jcansdale, which is why I asked for him to review it. In fact this one is special in that it pertains to td.net so none of the rest of us do commits here.

A pointer: if you don't know exactly __who__ to remind, it's better to just post without a name. Most team members will ignore something that seems to be "for" someone else. I just got curious when I saw all the "pokes."

**Comment by 304NotModified** [comment]
Because of this:

https://github.com/nunit/nunit/pull/3160#issuecomment-462148493

;)

**Comment by CharliePoole** [comment]
Ah! Sorry, I hunted for some prior conversation but couldn't find it. I'm sure @ChrisMaddock will nag the appropriate people for you. :smiley:

**Comment by ChrisMaddock** [comment]
Yeah, sorry - this one should wait for @jcansdale to review and merge.

When I said ‘adapter’ btw, I was referring to the VS adapter rather than the TDNET adapter - sorry I wasn’t clearer! This looks like a good PR to have here as well however, it’s just not for me to merge. 😊

**Pull request merged**
